# Generated by Django 4.2.6 on 2023-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="magasin",
            field=models.TextField(blank=True),
        ),
    ]
