# Generated by Django 4.2.6 on 2023-10-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_collaborator_age_collaborator_job_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="slug",
            field=models.SlugField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
